ci:
  collect:
    settings:
      preset: desktop
      startServerCommand: 'bun run start'

  assert:
    preset: lighthouse:no-pwa
    assertions:
      csp-xss: off # https://github.com/tszhong0411/honghong.me#%EF%B8%8F-todo
      bf-cache: off # no needed
      non-composited-animations: warn
      unminified-css: warn
      unused-css-rules: warn
      unused-javascript: warn
      uses-responsive-images: warn
