version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_honghong_me
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: honghong_me
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
