name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for 'skip ci' in commit messages
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[skip-ci]"* && "${{ github.actor }}" == "tszhong0411" ]]; then
            echo "CI checks are skipped as requested."
            exit 0
          fi

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Typecheck
        run: bun run type-check

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
