name: Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check setup
        uses: ./.github/actions/check-setup

      - name: Build the app
        run: pnpm build:apps

      - name: Check
        run: pnpm check
