name: End to end tests

on:
  pull_request:

jobs:
  test:
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check setup
        uses: ./.github/actions/check-setup

      - name: Build the app
        run: pnpm --filter=web build

      - name: Run Playwright tests
        uses: docker://mcr.microsoft.com/playwright:v1.44.1-jammy
        with:
          args: bash -c "npm install -g pnpm && corepack enable && env HOME=/root pnpm test:e2e"

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: apps/web/playwright-report/
          retention-days: 30
